version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    restart: always
    command:
      - "-c"
      - "max_connections=5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ariel
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
